# Generated by Django 4.2.3 on 2023-07-31 12:35

import PizzaProject.products.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[PizzaProject.products.validators.name_validator, django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('price', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('image', models.ImageField(upload_to='images/products/deserts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[PizzaProject.products.validators.name_validator, django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('price_small', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('price_large', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('small_image', models.ImageField(upload_to='images/products/images')),
                ('large_image', models.ImageField(upload_to='images/products/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[PizzaProject.products.validators.name_validator, django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('price_small', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('price_medium', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('price_large', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('price_extra_large', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('stripe_small_price_id', models.CharField(max_length=100)),
                ('stripe_medium_price_id', models.CharField(max_length=100)),
                ('stripe_large_price_id', models.CharField(max_length=100)),
                ('stripe_extra_large_price_id', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/pizzas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[PizzaProject.products.validators.name_validator, django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('price_small', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('price_large', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('image', models.ImageField(upload_to='images/products/salads')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
