# Generated by Django 4.2.3 on 2023-07-19 12:06

import PizzaProject.products.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), PizzaProject.products.validators.name_validator])),
                ('description', models.TextField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('small_price', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('large_price', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('image', models.ImageField(upload_to='images/products/salads')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/pizzas'),
        ),
    ]
