# Generated by Django 4.2.3 on 2023-07-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_salad_alter_pizza_description_alter_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salad',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
