# Generated by Django 4.2.3 on 2023-07-20 20:15

import PizzaProject.products.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_salad_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), PizzaProject.products.validators.name_validator])),
                ('description', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('price', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('image', models.ImageField(upload_to='images/products/deserts')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='salad',
            name='description',
            field=models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
