# Generated by Django 4.2.3 on 2023-07-20 21:06

import PizzaProject.products.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_desert_alter_pizza_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), PizzaProject.products.validators.name_validator])),
                ('small_price', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('large_price', models.FloatField(validators=[PizzaProject.products.validators.positive_price])),
                ('small_image', models.ImageField(upload_to='images/products/images')),
                ('large_image', models.ImageField(upload_to='images/products/images')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
    ]
