# Generated by Django 4.2.3 on 2023-07-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_drink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='large_price',
            new_name='price_large',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='small_price',
            new_name='price_small',
        ),
    ]
