# Generated by Django 4.2.3 on 2023-07-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_large_price_drink_price_large_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salad',
            old_name='large_price',
            new_name='price_large',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='small_price',
            new_name='price_small',
        ),
    ]
