# Generated by Django 4.2.3 on 2023-07-25 20:02

import PizzaProject.products.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_large_price_salad_price_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='description',
            field=models.TextField(default=1, max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desert',
            name='name',
            field=models.CharField(max_length=30, validators=[PizzaProject.products.validators.name_validator, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=30, validators=[PizzaProject.products.validators.name_validator, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='salad',
            name='name',
            field=models.CharField(max_length=30, validators=[PizzaProject.products.validators.name_validator, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
