# Generated by Django 4.2.3 on 2023-07-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_drink_description_alter_desert_name_alter_drink_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='stripe_extra_large_price_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='stripe_large_price_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='stripe_medium_price_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='stripe_small_price_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
