# Generated by Django 4.2.3 on 2023-07-31 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('product_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('size', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('single_price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('price_id', models.CharField(max_length=40)),
            ],
        ),
    ]
