# Generated by Django 4.2.3 on 2023-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('product_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
