# Generated by Django 4.2.3 on 2023-07-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='single_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
