# Generated by Django 4.2.3 on 2023-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='specific_order_id',
            field=models.CharField(blank=True, editable=False, max_length=60, null=True),
        ),
    ]
