# Generated by Django 4.2.3 on 2023-08-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderhistory_specific_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
