version: '3.4'

services:
  web:
    image: ramun3/pizza_order_app
    build: .
    command: gunicorn --bind=0.0.0.0:8000 PizzaProject.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env
    volumes:
      - /tmp/pizza_order_app/static:/app/static
      - ./media:/app/media
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Kradoslavov1994
      POSTGRES_USER: psihokiller3
      POSTGRES_DB: PizzaOrderingWebsiteNewest
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - /tmp/pizza_order_app/static:/home/app/web/staticfiles
      - ./media:/home/app/web/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web
  certbot:
    image: certbot/certbot
    command: certonly --webroot -w /var/www/certbot -d mammamia-pizzeria.online
    volumes:
      - /var/www/certbot:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx
