# Generated by Django 4.2.3 on 2023-07-19 08:54

import PizzaProject.profiles.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), PizzaProject.profiles.validators.letter_validator])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), PizzaProject.profiles.validators.letter_validator])),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(9), PizzaProject.profiles.validators.phone_validator])),
                ('city', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('address', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profiles/', validators=[PizzaProject.profiles.validators.validate_file_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
